name=EvoArm
version=1.8.0
author=Evodyne Robotics Academy <support@evodyneacademy.com>
maintainer=Evodyne Robotics Academy <support@evodyneacademy.com>
sentence=EvoArm Library
paragraph=EvoArm Library
category=Other
url=https://evodyneacademy.com
architectures=*
